import React from 'react';import{createRoot}from'react-dom/client';import{Search,Lock,ArrowRight,Star,Users,PlayCircle,BookOpen,BarChart3,Palette,BriefcaseBusiness,Camera,Code2,Facebook}from'lucide-react';import'./style.css';
const cats=['Featured','Video','Drawing & Painting','Marketing','Animation','Social Media','UI/UX Design','Content Writing','Digital Illustration','Film & Video','Crafts','Freelance & Entrepreneurship','Graphic Design','Photography','Productivity','Web Development','Data Science','Coaching','More'];
const courses=[['Learn Figma from Basic','course-figma.png','1.5 hr'],['Build Digital Asset','course-data.png','4.2 hr'],['the Power of Big Data','course-data.png','4.5 hr'],['Balancing Productivity and...','course-office.png','4.5 hr'],['Mastering Money Manage...','course-finance.png','4.2 hr'],['From Idea to Startup Succ...','course-team.png','4.5 hr']];
function Logo(){return <a className="logo" href="#"><span className="mark">b</span> ByteSpace</a>}
function Header(){return <header><Logo/><nav><a href="#courses">Home</a><a href="#courses">Courses</a><a href="#about">About</a></nav><div className="actions"><a href="/login.html">Sign In</a><a className="lock" href="/register.html">Join Us <Lock size={14}/></a></div></header>}
function Hero(){return <section className="hero"><Header/><div className="shape s1"></div><div className="shape s2"></div><div className="heroCopy"><h1>Get Access to Hundreds<br/>Courses Available</h1><p>Unlock your creativity, gain valuable knowledge, and grow your skills with ByteSpace.</p><div className="search"><Search size={17}/><input placeholder="Course, topic, creator"/><button>Search</button></div></div><div className="heroVisual"><div className="bubble b1">UI/UX Design<br/><b>12 Lessons · 2 hours</b></div><div className="bubble b2">Learning Progress<br/><strong>55%</strong><span></span></div><img src="/assets/hero-person.png"/></div></section>}
function Logos(){return <div className="logos">{[1,2,3,4,5].map(i=><div key={i}><span>◉</span> LogoIpsum</div>)}</div>}
function CourseCard({c}){return <article className="course"><img src={'/assets/'+c[1]}/><div className="chips"><span>17 Lessons</span><span>2 hours 16 mins</span></div><h3>{c[0]}</h3><div className="meta"><span>by <b>purepearl studio</b></span><span>{c[2]} ★</span></div><div className="people">● ● ● ● <i>26+</i></div><strong className="price">$25<small>/lifetime</small></strong></article>}
function Courses(){return <section className="section" id="courses"><h2>Discover Your Passion,<br/>Build Your Skills</h2><p className="sub">At ByteSpace Courses, we bring you closer to life-changing knowledge. Explore a variety of courses across different fields.</p><div className="filters">{cats.map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div><div className="grid">{courses.map((c,i)=><CourseCard c={c} key={i}/>)}</div></section>}
const paths=[[Palette,'Design'],[Code2,'Development'],[Code2,'IT & Software'],[BriefcaseBusiness,'Business'],[BarChart3,'Marketing'],[Camera,'Photography']];
function Paths(){return <section className="section paths"><h2>Explore Diverse Learning Paths at Bytespace</h2><p className="sub">At ByteSpace, we believe in empowering individuals through knowledge. Our chosen range of courses spans various fields.</p><div className="pathrow">{paths.map(([I,t])=><div><i><I size={22}/></i><span>{t}</span></div>)}</div></section>}
function Feature(){return <section className="feature" id="about"><div className="featureRow"><div><h2>Your Path to Professional<br/>Growth Starts Here!</h2><p>Explore our curated selection of courses to learn in a format that fits your life. From essential foundations to practical skills, gain industry-relevant experience and move forward with confidence.</p><div className="stats"><b>12K<small>Students</small></b><b>70+<small>Courses</small></b><b>16<small>Creators</small></b></div></div><img src="/assets/growth-person.png"/></div><div className="featureRow reverse"><img src="/assets/creator-person.png"/><div><h2>Create & Manage<br/>Courses Easily.</h2><p>ByteSpace supports creators with a simple, polished, and administration-friendly experience.</p><ul><li>Share Your Expertise</li><li>Monetize Your Passion</li><li>Flexibility and Autonomy</li><li>Build a Community</li></ul></div></div></section>}
function CTA(){return <section className="cta"><h2>Unlock Your Potential as a<br/>Creator with ByteSpace</h2><p>Expertise is valuable and your unique insights can empower learners everywhere. Join our creator community today.</p><button>Join as Creator</button></section>}
const reviews=[['Sarah M.','Enthusiastic Learner','“ByteSpace has made learning accessible to everyone. The diverse range of courses and the ability to learn anytime is genuinely helpful.”'],['James L.','Lifelong Learner','“I’ve discovered skills I never thought I’d pursue. The platform is clean, focused, and easy to keep coming back to.”'],['Alex B.','Inspired Creator','“As a creator, ByteSpace has been a game-changer. I can share what I know and connect with a growing community.”']];
function Community(){return <section className="community"><div className="communityHead"><h2>Discover What Our<br/>Community Is Saying</h2><p>At ByteSpace, we foster a community of learners and creators. Hear from people who use the platform to learn, teach, and grow.</p></div><div className="reviews">{reviews.map((r,i)=><article><div className="avatar">{r[0][0]}</div><b>{r[0]}</b><a>{r[1]}</a><p>{r[2]}</p></article>)}</div></section>}
function Footer(){return <footer><div><Logo/><p>Stay ByteSpace and never miss a new course or creator.</p><div className="newsletter"><input placeholder="Enter your email"/><button>Send</button></div></div><div><b>Explore Courses</b><a>Popular</a><a>Featured</a><a>New</a></div><div><b>About Us</b><a>About</a><a>Privacy</a><a>Terms</a></div><div><b>Support & Contact</b><a>Help Center</a><a>Contact</a><a>FAQ</a></div></footer>}
function App(){return <><Hero/><Logos/><Courses/><Paths/><Feature/><CTA/><Community/><Footer/></>};createRoot(document.getElementById('root')).render(<App/>);